[workspace]
members = [
    'node',
    'runtime',
    'pallets/timestake',
    'metascore',
    'VrmetaxFPS',
    'VrmetaxRPG',
    'pixelland_map',
    'pallets/chainless_mint_iou',
]
[profile.release]
panic = 'unwind'


