[package]
name = "pallet-staking"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME pallet staking"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.136", optional = true }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }
sp-std = { version = "4.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-io = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate"}
sp-runtime = { version = "6.0.0", default-features = false, pgit = "https://github.com/paritytech/substrate" }
sp-staking = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate" }
frame-support = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate"}
frame-system = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate" }
pallet-session = { version = "4.0.0-dev", default-features = false, features = [
	"historical",
], git = "https://github.com/paritytech/substrate" }
pallet-authorship = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate" }
sp-application-crypto = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate" }
frame-election-provider-support = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate" }
log = { version = "0.4.14", default-features = false }

# Optional imports for benchmarking
frame-benchmarking = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", optional = true }
rand_chacha = { version = "0.2", default-features = false, optional = true }

[dev-dependencies]
sp-tracing = { version = "5.0.0", git = "https://github.com/paritytech/substrate" }
sp-core = { version = "6.0.0", git = "https://github.com/paritytech/substrate" }
sp-npos-elections = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate" }
pallet-balances = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate" }
pallet-timestamp = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate" }
pallet-staking-reward-curve = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate" }
pallet-bags-list = { version = "4.0.0-dev", features = ["runtime-benchmarks"], git = "https://github.com/paritytech/substrate" }
substrate-test-utils = { version = "4.0.0-dev",  git = "https://github.com/paritytech/substrate"}
frame-benchmarking = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate" }
frame-election-provider-support = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate" }
rand_chacha = { version = "0.2" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"scale-info/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-session/std",
	"frame-system/std",
	"pallet-authorship/std",
	"sp-application-crypto/std",
	"log/std",
	"frame-election-provider-support/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-election-provider-support/runtime-benchmarks",
	"rand_chacha",
]
try-runtime = ["frame-support/try-runtime"]
